# Generated by Django 3.2 on 2021-07-07 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('descuento', models.IntegerField()),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='suscriptUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('descripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.suscripcion')),
            ],
        ),
    ]
